### PR TITLE
OneDrive

### PR DESCRIPTION
**Pull request by dkhamsing**
Hey Caleb, here's the OneDrive provider which has OAuth through Microsoft Live with a specific scope for storage permissions http://onedrive.github.io 

`- isTargetRedirectURL:` seems a bit fragile but it works in the example app

I left out the Podfile.lock, I'm not sure how that thing is generated :smile:

### CODE REVIEW

**Comment by calebd** [comment]
How is `isTargetRedirectURL:` fragile?

**Comment by calebd** [comment]
Oh I see what you're saying. So the default implementation of that method does the following:

```objc
- (BOOL)isTargetRedirectURL:(NSURL *)URL {
    NSString *targetURLString = [self.options[SimpleAuthRedirectURIKey] lowercaseString];
    NSString *actualURLString = [[URL absoluteString] lowercaseString];
    return [actualURLString hasPrefix:targetURLString];
}
```

So it's not strictly necessary for you to do the same. If you know it will always be `https://live.com` or whatever, just set that as a default option on the provider and the framework will handle it for you.

**Comment by dkhamsing** [comment]
On http://onedrive.github.io/auth/msa_oauth.htm if you look at `Step 1. Get an authentication code` /  `Response`, the auth code is supposed to come back as

`
https://login.live.com/oauth20_authorize.srf?code=df6aa589-1080-b241-b410-c4dff65dbf7c
`

However, I have found in my testing that it came out as

`
http://eeb6f219-0ae3-4197-852a-2c5de29a26cd.apps.dev.live.com/?code=5c69a65a-21b3-fd1b-b721-c5de1d597be6
`

Maybe it is simply a matter of dev vs production app.. Would `?code=` work for both?

**Comment by dkhamsing** [comment]
Uh yeah I meant my implementation of `- isTargetRedirectURL:`

**Comment by calebd** [comment]
Oh that sucks. Ok, your way is fine then. One change, if you could, use the old `rangeOfString` method instead of `containsString` since that is an iOS 8 only API.

Otherwise looks good to me!

**Comment by dkhamsing** [comment]
Right right.. got it

**Comment by calebd** [comment]
Thanks!!

**Comment by dkhamsing** [comment]
:smile:

**Pull request merged**
