### PR TITLE
Box

### PR DESCRIPTION
**Pull request by dkhamsing**
Hey Caleb, would love for you to take a look

I tested this successfully with the example app although setting up Box to work in an app requires a special redirect URI in the format `boxsdk-YOUR_CLIENT_ID://boxsdkoauth2redirect` ([source](https://github.com/box/box-ios-sdk-v2))

As you can see, we can get the redirect URI from the CLIENT_ID but I couldn't get this to work so for now, you have to set 

``` objc
    NSString *boxClientId = @"CLIENT_ID";
    SimpleAuth.configuration[@"box-web"] = @{
                                             @"client_id":boxClientId,
                                             @"client_secret":@"CLIENT_SECRET",
                                             @"redirect_uri" : [NSString stringWithFormat:@"boxsdk-%@://boxsdkoauth2redirect", boxClientId],
                                             };
```

### CODE REVIEW

**Comment by calebd** [comment]
Can the provider automatically synthesize the box redirect url for you? That seems like something the consumer should not have to do.

**Comment by calebd** [comment]
Oh wait you're saying you tried that and it didn't work?

**Comment by dkhamsing** [comment]
Yes the provider should do it.. I was trying to update `self.options` but it is `readonly`.. should I override the getter for `options` ?

**Comment by calebd** [comment]
Do you need to store it in options or can you just synthesize it where it is needed?

**Comment by dkhamsing** [comment]
Well I know it need it in the target url check `isTargetRedirectURL`, what do guy recommended

**Comment by calebd** [comment]
If you only need it in the web view controller, I would make a mutable copy of `self.options`, synthesize the value, and pass that new dictionary to the view controller initializer. Then the view controller can include it in the initial request as well as the url check.

If you need it in other places, consider making a private, read-only property in the provider that returns the synthesized value that you can use elsewhere.

I would not override the options accessor or try to mutate it. It is immutable for a reason.

**Comment by calebd** [comment]
Actually, you can override `initWithOptions:`, copy and mutate the dictionary, then call super with the new value there and it will be usable everywhere in the provider.

**Comment by dkhamsing** [comment]
Will try, thanks

**Comment by dkhamsing** [comment]
Hey Caleb, the provider now takes care of redirect URI so the user can just set

``` objc
 SimpleAuth.configuration[@"box-web"] = @{
                                             @"client_id":@"CLIENT_ID"
                                             @"client_secret":@"CLIENT_SECRET",
                                             };
```

**Comment by dkhamsing** [comment]
There's a bit of code duplication for how that redirect URI is generated, let me know if that's ok or how it could be improved (class method on `SimpleAuthBoxWebLoginViewController`?)

**Comment by calebd** [comment]
I flattened the `redirect_uri` building by moving it into `-[SimpleAuthBoxWebProvider initWithOptions:]`. This way the `redirect_uri` is calculated only once and is available everywhere in the provider and its login view controller.

Would you mind pulling my `box` branch and testing it out?

The specific change can be seen in 35e9ea52e00af02777eeab4d7e3440d2516fbc5c if you are curious.

**Comment by calebd** [comment]
If it looks good to you I'll merge the branch into `master` and close the pull request. Thanks for your work on this!

**Comment by dkhamsing** [comment]
Ok will try it out

**Comment by dkhamsing** [comment]
Uh..

**Comment by calebd** [comment]
Your commits are now in master. You didn't pull the right branch from my repo into yours so none of the changes I made where in here. Just easier to merge it myself and close.

**Comment by calebd** [comment]
Which now leads me to wonder: did you check out my `box` branch and the commit I referenced, or did you only pull `master`? If not the change I made might not be correct. I don't have a box account so I am unable to verify.

**Comment by dkhamsing** [comment]
Oops sorry thought I did https://github.com/dkhamsing/SimpleAuth/commit/8f272b48c245df8cacef88cd611f2e71f30f26b0 thanks for your work

**Comment by dkhamsing** [comment]
Caleb I tested master, we are all good

**Comment by calebd** [comment]
Awesome! Thanks again for your work on this!

**Comment by dkhamsing** [comment]
:smile:

**Pull request closed without merging**
