### PR TITLE
GitHub

### LINKED ISSUE #16: GitHub provider

### PR DESCRIPTION
**Pull request by dkhamsing**
Will need to update Podfile.lock :smile: 

Close #16

### CODE REVIEW

**Comment by calebd** [comment]
You're on a roll!

**Comment by dkhamsing** [comment]
Were you able to try it out

**Comment by dkhamsing** [comment]
Hm looks like there's a bug in there.. will fix it :confused:

**Comment by dkhamsing** [comment]
A little better :grin:

**Comment by dkhamsing** [comment]
Thx, removed

**Comment by dkhamsing** [comment]
*poke* :smile:

**Comment by sammdec** [comment]
Any update if this is planned on being merged sometime soon?

**Comment by zackkitzmiller** [comment]
Any update on this? Would love to get it merged in.

**Pull request closed without merging**
